name: Manual API Docs Scraper

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running the scraper'
        required: false
        default: 'Regular update'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go mod tidy

      - name: Run scraper
        run: go run main.go

      - name: Commit and push if there are changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update API documentation - ${{ github.event.inputs.reason }}" && git push) 